### ISSUE TITLE
Fix initial zoom on map to be responsive to dataset

### ISSUE THREAD

**Issue by rsoden** [openoakland/woaq#17]
low priority but would be nice

**Comment by rsoden** [comment]
Currently line 42 in _templates/data.html is:  center: [-122.288356, 37.813146]. 

Instead of this, we should load the geojson file (stored in the file_loc jekyll variable) and use a  MapboxGL function to determine its extent.

**Comment by TangoYankee** [comment]
**Resources/Documentation**
- [MapboxGL JavaScript](https://www.mapbox.com/mapbox-gl-js/api/)

**Comment by Ethan-bradley** [comment]
The heatmap is now responsive to zooming.
