### ISSUE TITLE
Set Default Branch

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woaq#27]
**Description**
- The master branch and gh-pages branches both hold different applications
- The master branch is currently set as the default
- The majority of updates may affect the gh-pages branch
   - Developers may be forced to continually switch branches and check for the correct branch

**Fix Action**
- [x] Set gh-pages as the default branch
     - Settings ▶️ Branches ▶️ Default Branch

**Comment by apengwin** [comment]
that's a bold move. and probably correct.

**Comment by apengwin** [comment]
Done
