### ISSUE TITLE
Split Projects from Branches into Repositories

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/woaq#30]
## Description

WOAQ repository is pulling double duty, holding python and ruby projects in master and gh-pages branches. Ethan Bradley already has a dedicated WoaqUploadAppCode Repository

1. Fork @Ethan-bradley 's [WoaqUploadAppCode Repository](https://github.com/Ethan-bradley/WoaqUploadAppCode) into a Common Repository at @openoakland 
2. Resolve differences between OpenOakland/WoaqUploadAppCode created from Ethan-bradley/WoaqUploadAppCode and Version held in Master Branch of [openoaklan/woaq](https://github.com/openoakland/woaq/tree/master)
3. Save all other relevant Python code into OpenOakland/WoaqUploadAppCode master branch. 
    * i.e) There should only be one Python project which manages all of the relevant functions
4. Delete all code from OpenOakland/Woaq that does not directly support the Jekyll Site

**Comment by Ethan-bradley** [comment]
This will be done after permission is gained.

**Comment by TangoYankee** [comment]
New strategy: Rebuild project from scratch, referencing code from two existing repositories.
